### PR TITLE
Adding functionality to watch files in "src" directory and re-run the TypeScript build when they change

### PR DESCRIPTION
**Pull request by BradleyCulley**
This is accomplished via the "npm-watch" npm package.
This allows iterative local development workflows like this:
1. run "npm run watch"
2. the type checker and build js files processes will run
3. the process will block, and watch the files in "src" for changes
4. if a file in "src" changes, go to step #2

### CODE REVIEW

**Comment by BradleyCulley** [comment]
@DanielRosenwasser @a-tarasyuk @matijs - I ran into a desire to do this while working with this repo. Thought I would create a PR in case this is something you'd like to capture in the repo. If not, apologies for the disturbance, and keep up the great work with TypeScript :)

**Comment by BradleyCulley** [comment]
@DanielRosenwasser @a-tarasyuk @matijs thought I'd loop back on this PR

**Comment by orta** [comment]
Thanks for the ping. 

I think we want to keep the repo focused solely on trying to describe how to use Babel + TS and not as more general bootstrapping example - in which case having more infra doesn't add too much value for people learning.

**Comment by BradleyCulley** [comment]
> Thanks for the ping.
> 
> I think we want to keep the repo focused solely on trying to describe how to use Babel + TS and not as more general bootstrapping example - in which case having more infra doesn't add too much value for people learning.

That makes sense - I'll close this PR. Thanks for the reply and keep up the great work on TypeScript.

**Pull request closed without merging**
