### PR TITLE
update typescript version

### PR DESCRIPTION
**Pull request by Ore4444**
emitDeclarationOnly is only supported after 2.8.3

### CODE REVIEW

**Comment by drgroot** [comment]
You also need to update the README.md where you run the command npm install --save-dev

**Comment by capaj** [comment]
@drgroot maybe it would be better to just don't specify the versions on install so that this guide doesn't have to be updated every time a new version comes out? See #13

**Comment by drgroot** [comment]
@capaj  that would work assuming the latest version received by npm of each package work without issues. However, that is not always the case. For example, exclduing the beta version on the babel packages would prove to be fatal.

**Comment by DanielRosenwasser** [comment]
We should be updated to 3.0 now, but thanks for the PR!

**Pull request closed without merging**
