### PR TITLE
add rollup example

### PR DESCRIPTION
**Pull request by a-tarasyuk**
@DanielRosenwasser this PR contains README changes, dependencies update and adding example how to setup Rollup with Babel and TypeScript.

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser could you review this PR?

**Comment by DanielRosenwasser** [comment]
Thanks for the PR! Any idea of Rollup can automatically generate the `.d.ts` files using some sort of integration?

**Comment by a-tarasyuk** [comment]
@DanielRosenwasser Thanks for your updates. I think Rollup cannot automatically generate the .d.ts, need to use some plugins which work with [_typescript_](https://www.npmjs.com/package/rollup-plugin-typescript2), however, `tsc` works well for generating/checking typings., `babel` adds flexibility to transpiling code _(we can use any optimization plugins, etc.)_ and we can avoid additional transpilation steps., each tool works well on the appropriate task :). I think we can avoid adding additional dependency because it just simplifies one npm script task 

before
```json
"build": "npm run build:types && npm run build:js"
```

after
```json
"build": "npm run build:js"
```

What do you think?

**Comment by DanielRosenwasser** [comment]
I think what we've got here is great. Thanks for the PR!

**Pull request merged**
